---
- name: restore switches
  hosts: sw2
  gather_facts: false
  #vars:
   # ansible_ssh_extra_args: "-oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-rsa"

  tasks:
    - name: copy running config
      command: >
        scp
        -oKexAlgorithms=+diffie-hellman-group1-sha1
        -oHostKeyAlgorithms=+ssh-rsa
        ./backup/{{ inventory_hostname }}.config
        admin@{{ inventory_hostname }}:{{ inventory_hostname }}.config

    - name: config replace
      remote_user: admin
      ios_command:
        commands:
          - config replace flash:{{ inventory_hostname }}.config force
