- name: Restore switches
  hosts: sw1:sw2
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Copy config to switch via SCP
      ansible.builtin.shell: |
        scp ./backup/{{ inventory_hostname }}.config admin@{{ inventory_hostname }}:{{ inventory_hostname }}.config
      delegate_to: localhost

    - name: Replace running config with backup
      cisco.ios.ios_command:
        commands:
          - config replace flash:{{ inventory_hostname }}.config force
