all:
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_password: udane95
    ansible_user: ansible
    #ansible_ssh_private_key_file: ~/.ssh/id_rsa
    #ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no'


  children:
    network:
      hosts:
        sw2:
        sw3:
        sw1:
        sw4:
    osversion:
      hosts:
        sw2:
        sw1:
    switchs:
      hosts:
        sw1:
          #ansible_host: 192.168.3.25
          #ansible_user: ansible
          #ansible_ssh_private_key_file: /home/user/.ssh/id_rsa
          #env: test
        sw3:
        sw2:
          #ansible_host: 192.168.3.29
          #ansible_user: ansible
          #env: test

