- name: recuperation des informations de la machine
  hosts: network
  gather_facts: no
  tasks:
    - name: Afficher les interfaces utilisées
      debug:
        var: interfaces
    - name:  affectation des vlan aux interfaces
      template:
        src: affectation_vlan.j2
        dest: /etc/ansible/cisco/jinja2.cfg
